kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-client-db-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
