apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  selector:
    app: nginx2
  type: LoadBalancer
#  type: NodePort
  ports:
    - port: 80
#      nodePort: 30000
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx2
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: pvc-nginx
